//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodoro.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string AboutStr {
            get {
                return ResourceManager.GetString("AboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        internal static string AppearanceStr {
            get {
                return ResourceManager.GetString("AppearanceStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CancelStr {
            get {
                return ResourceManager.GetString("CancelStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as current.
        /// </summary>
        internal static string CurrentSetStr {
            get {
                return ResourceManager.GetString("CurrentSetStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Task.
        /// </summary>
        internal static string CurrentTaskStr {
            get {
                return ResourceManager.GetString("CurrentTaskStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeleteStr {
            get {
                return ResourceManager.GetString("DeleteStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        internal static string DoneStr {
            get {
                return ResourceManager.GetString("DoneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string EditStr {
            get {
                return ResourceManager.GetString("EditStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execution Date.
        /// </summary>
        internal static string ExecutionDateStr {
            get {
                return ResourceManager.GetString("ExecutionDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the date of a scheduled task.
        /// </summary>
        internal static string ExNewDateStr {
            get {
                return ResourceManager.GetString("ExNewDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Done.
        /// </summary>
        internal static string IsDoneStr {
            get {
                return ResourceManager.GetString("IsDoneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string LanguageStr {
            get {
                return ResourceManager.GetString("LanguageStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long break.
        /// </summary>
        internal static string LongBreakStr {
            get {
                return ResourceManager.GetString("LongBreakStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long break time.
        /// </summary>
        internal static string LongBreakTimeStr {
            get {
                return ResourceManager.GetString("LongBreakTimeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Task.
        /// </summary>
        internal static string NewTaskStr {
            get {
                return ResourceManager.GetString("NewTaskStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string NextStr {
            get {
                return ResourceManager.GetString("NextStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pomodoro Timer.
        /// </summary>
        internal static string PomodoroTimer {
            get {
                return ResourceManager.GetString("PomodoroTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previos.
        /// </summary>
        internal static string PreviosStr {
            get {
                return ResourceManager.GetString("PreviosStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High.
        /// </summary>
        internal static string PriorityHighStr {
            get {
                return ResourceManager.GetString("PriorityHighStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low.
        /// </summary>
        internal static string PriorityLowStr {
            get {
                return ResourceManager.GetString("PriorityLowStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal.
        /// </summary>
        internal static string PriorityNormalStr {
            get {
                return ResourceManager.GetString("PriorityNormalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Urgent.
        /// </summary>
        internal static string PriorityUrgentStr {
            get {
                return ResourceManager.GetString("PriorityUrgentStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration Date.
        /// </summary>
        internal static string RegistrationDateStr {
            get {
                return ResourceManager.GetString("RegistrationDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveStr {
            get {
                return ResourceManager.GetString("SaveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsStr {
            get {
                return ResourceManager.GetString("SettingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short break.
        /// </summary>
        internal static string ShortBreakStr {
            get {
                return ResourceManager.GetString("ShortBreakStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short break time.
        /// </summary>
        internal static string ShortBreakTimeStr {
            get {
                return ResourceManager.GetString("ShortBreakTimeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string StartStr {
            get {
                return ResourceManager.GetString("StartStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string TaskDescriptionStr {
            get {
                return ResourceManager.GetString("TaskDescriptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority.
        /// </summary>
        internal static string TaskPriorityStr {
            get {
                return ResourceManager.GetString("TaskPriorityStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of pomodoros spent.
        /// </summary>
        internal static string TaskSpentPomodorosStr {
            get {
                return ResourceManager.GetString("TaskSpentPomodorosStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        internal static string TasksStr {
            get {
                return ResourceManager.GetString("TasksStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        internal static string TaskStateStr {
            get {
                return ResourceManager.GetString("TaskStateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string TaskStatusStr {
            get {
                return ResourceManager.GetString("TaskStatusStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string TaskTitleStr {
            get {
                return ResourceManager.GetString("TaskTitleStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        internal static string ThemeStr {
            get {
                return ResourceManager.GetString("ThemeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer Setting.
        /// </summary>
        internal static string TimerSettingStr {
            get {
                return ResourceManager.GetString("TimerSettingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer.
        /// </summary>
        internal static string TimerStr {
            get {
                return ResourceManager.GetString("TimerStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn monitor Off.
        /// </summary>
        internal static string TurnMonitorOffStr {
            get {
                return ResourceManager.GetString("TurnMonitorOffStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn sound on.
        /// </summary>
        internal static string TurnSoundOnStr {
            get {
                return ResourceManager.GetString("TurnSoundOnStr", resourceCulture);
            }
        }
    }
}
